[project]
name = "experimental"
version = "0.1.0"
description = "GradBoxLLM Experimental pyenv."
readme = "README.md"
requires-python = "==3.11.11"
dependencies = [
    "ipykernel>=6.29.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
